# Generated by Django 5.2.1 on 2025-05-30 13:59

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400, verbose_name='Name')),
                ('abn', models.CharField(max_length=15, verbose_name='ABN')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('address', models.TextField(verbose_name='Address')),
                ('payment_allowance', models.IntegerField(verbose_name='Payment Allowance (days)')),
                ('pay_rate', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Pay Rate')),
                ('payment_terms', models.TextField(verbose_name='Payment Terms')),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_num', models.CharField(unique=True, verbose_name='Invoice #')),
                ('gen_date', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('pay_date', models.DateField(verbose_name='Due Date')),
                ('payment_terms', models.TextField(verbose_name='Payment Terms')),
                ('is_paid', models.BooleanField(verbose_name='Paid')),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(verbose_name='Description')),
                ('description_extra', models.CharField(verbose_name='Extended Description')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Rate/hr')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Hours')),
                ('total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pjimcrm.invoice')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(verbose_name='Name')),
                ('description', models.CharField(verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pjimcrm.client')),
            ],
        ),
        migrations.CreateModel(
            name='TimesheetEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(verbose_name='Description')),
                ('description_set', models.BooleanField(verbose_name='Description has been set')),
                ('time_seconds', models.IntegerField(verbose_name='Length (seconds)')),
                ('timestamp_started', models.DateTimeField(verbose_name='Time Started')),
                ('timestamp_stopped', models.DateTimeField(verbose_name='Time Stopped')),
                ('timestamp_started_old', models.DateTimeField(verbose_name='Previously Started')),
                ('timestamp_stopped_old', models.DateTimeField(verbose_name='Previously Stopped')),
                ('is_invoiced', models.BooleanField(verbose_name='Invoiced')),
                ('invoice_reference', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pjimcrm.invoice')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='pjimcrm.project')),
                ('target_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
