# Generated by Django 5.2.1 on 2025-06-20 10:07

import datetime
import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=400, verbose_name="Name")),
                ("abn", models.CharField(max_length=15, verbose_name="ABN")),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
                ("address", models.TextField(blank=True, verbose_name="Address")),
                ("payment_allowance", models.PositiveSmallIntegerField(verbose_name="Payment Allowance (days)")),
                ("pay_rate", models.DecimalField(decimal_places=2, max_digits=10, verbose_name="Pay Rate")),
                ("payment_terms", models.TextField(verbose_name="Payment Terms")),
                ("created_date", models.DateTimeField(auto_now_add=True, verbose_name="Created Date")),
                ("modified_date", models.DateTimeField(auto_now=True, verbose_name="Modified Date")),
            ],
        ),
        migrations.CreateModel(
            name="Invoice",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("invoice_num", models.CharField(unique=True, verbose_name="Invoice #")),
                (
                    "invoice_uuid",
                    models.UUIDField(default=uuid.UUID("e327b6fe-6ade-4266-ae34-8126b1b31855"), verbose_name="UUID"),
                ),
                ("gen_date", models.DateField(default=datetime.date.today, verbose_name="Date")),
                ("pay_date", models.DateField(verbose_name="Due Date")),
                ("payment_terms", models.TextField(verbose_name="Payment Terms")),
                ("is_paid", models.BooleanField(default=False, verbose_name="Paid")),
                ("created_date", models.DateTimeField(auto_now_add=True, verbose_name="Created Date")),
                ("modified_date", models.DateTimeField(auto_now=True, verbose_name="Modified Date")),
                ("client", models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to="pjimcrm.client")),
            ],
        ),
        migrations.CreateModel(
            name="InvoiceLine",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("description", models.CharField(verbose_name="Description")),
                ("description_extra", models.CharField(verbose_name="Extended Description")),
                ("price", models.DecimalField(decimal_places=2, max_digits=10, verbose_name="Rate/hr")),
                ("quantity", models.DecimalField(decimal_places=3, max_digits=10, verbose_name="Hours")),
                ("total", models.DecimalField(decimal_places=2, max_digits=10, verbose_name="Total")),
                ("created_date", models.DateTimeField(auto_now_add=True, verbose_name="Created Date")),
                ("modified_date", models.DateTimeField(auto_now=True, verbose_name="Modified Date")),
                ("invoice", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="pjimcrm.invoice")),
            ],
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(verbose_name="Name")),
                ("description", models.CharField(verbose_name="Description")),
                ("is_active", models.BooleanField(default=True, verbose_name="Is Active")),
                ("created_date", models.DateTimeField(auto_now_add=True, verbose_name="Created Date")),
                ("modified_date", models.DateTimeField(auto_now=True, verbose_name="Modified Date")),
                ("client", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="pjimcrm.client")),
            ],
        ),
        migrations.CreateModel(
            name="TimesheetEntry",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("description", models.CharField(verbose_name="Description")),
                ("description_set", models.BooleanField(default=False, verbose_name="Description has been set")),
                ("entry_date", models.DateField(default=datetime.date.today, verbose_name="Date")),
                ("length_raw", models.DurationField(default=datetime.timedelta(0), verbose_name="Length (raw)")),
                (
                    "length_rounded",
                    models.DurationField(default=datetime.timedelta(0), verbose_name="Length (rounded)"),
                ),
                ("timestamp_started", models.DateTimeField(blank=True, null=True, verbose_name="Time Started")),
                ("timestamp_stopped", models.DateTimeField(blank=True, null=True, verbose_name="Time Stopped")),
                (
                    "timestamp_started_old",
                    models.DateTimeField(blank=True, null=True, verbose_name="Previously Started"),
                ),
                (
                    "timestamp_stopped_old",
                    models.DateTimeField(blank=True, null=True, verbose_name="Previously Stopped"),
                ),
                ("is_invoiced", models.BooleanField(default=False, verbose_name="Invoiced")),
                ("created_date", models.DateTimeField(auto_now_add=True, verbose_name="Created Date")),
                ("modified_date", models.DateTimeField(auto_now=True, verbose_name="Modified Date")),
                (
                    "invoice_reference",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="pjimcrm.invoice"
                    ),
                ),
                ("project", models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to="pjimcrm.project")),
                (
                    "target_user",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
    ]
