# Generated by Django 5.2.4 on 2025-11-29 02:03

import django.db.models.deletion
import pjimcrm.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pjimcrm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayToDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(verbose_name='Name')),
                ('recipient_name', models.CharField(blank=True, verbose_name='Recipient Name')),
                ('abn', models.CharField(blank=True, default='', verbose_name='ABN')),
                ('email', models.CharField(blank=True, default='', verbose_name='Email')),
                ('address', models.TextField(blank=True, default='', verbose_name='Address')),
                ('bsb', models.CharField(blank=True, default='', verbose_name='BSB')),
                ('account_number', models.CharField(blank=True, default='', verbose_name='Account Number')),
                ('weight', models.IntegerField(default=0, verbose_name='Weight')),
            ],
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_uuid',
            field=models.UUIDField(default=uuid.UUID('4dd45729-5faf-4f1a-979c-d848afad8781'), verbose_name='UUID'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='pay_to',
            field=models.ForeignKey(default=pjimcrm.models.default_pay_to, on_delete=django.db.models.deletion.RESTRICT, to='pjimcrm.paytodetails'),
        ),
    ]
