# Generated by Django 5.2.1 on 2025-06-02 15:30

import datetime
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pjimcrm', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timesheetentry',
            name='time_seconds',
        ),
        migrations.AddField(
            model_name='client',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Created Date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='modified_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Modified Date'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Created Date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoice',
            name='invoice_uuid',
            field=models.UUIDField(default=uuid.UUID('1ff26f97-5aa4-4d0a-b434-f03b3569da40'), verbose_name='UUID'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='modified_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Modified Date'),
        ),
        migrations.AddField(
            model_name='invoiceline',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Created Date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoiceline',
            name='modified_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Modified Date'),
        ),
        migrations.AddField(
            model_name='project',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Created Date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='modified_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Modified Date'),
        ),
        migrations.AddField(
            model_name='timesheetentry',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Created Date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='timesheetentry',
            name='length_raw',
            field=models.DurationField(default=datetime.timedelta(0), verbose_name='Length (raw)'),
        ),
        migrations.AddField(
            model_name='timesheetentry',
            name='length_rounded',
            field=models.DurationField(default=datetime.timedelta(0), verbose_name='Length (rounded)'),
        ),
        migrations.AddField(
            model_name='timesheetentry',
            name='modified_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Modified Date'),
        ),
        migrations.AlterField(
            model_name='timesheetentry',
            name='timestamp_started',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Time Started'),
        ),
        migrations.AlterField(
            model_name='timesheetentry',
            name='timestamp_started_old',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Previously Started'),
        ),
        migrations.AlterField(
            model_name='timesheetentry',
            name='timestamp_stopped',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Time Stopped'),
        ),
        migrations.AlterField(
            model_name='timesheetentry',
            name='timestamp_stopped_old',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Previously Stopped'),
        ),
    ]
