# Generated by Django 5.2.1 on 2025-06-04 13:35

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pjimcrm', '0002_remove_timesheetentry_time_seconds_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='address',
            field=models.TextField(blank=True, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_uuid',
            field=models.UUIDField(default=uuid.UUID('0ad4a69a-086b-4d8c-af17-9bb7a77635f0'), verbose_name='UUID'),
        ),
    ]
