# Generated by Django 5.2.1 on 2025-06-04 13:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pjimcrm', '0003_alter_client_address_alter_invoice_invoice_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='client',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.RESTRICT, to='pjimcrm.client'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_uuid',
            field=models.UUIDField(default=uuid.UUID('213601e4-10b7-4eb5-8933-44d5ee3f12e4'), verbose_name='UUID'),
        ),
    ]
