# Generated by Django 5.2.1 on 2025-06-20 09:58

import datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pjimcrm', '0004_invoice_client_alter_invoice_invoice_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='timesheetentry',
            name='entry_date',
            field=models.DateField(default=datetime.datetime(2025, 6, 20, 9, 58, 22, 684610, tzinfo=datetime.timezone.utc), verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='client',
            name='payment_allowance',
            field=models.PositiveSmallIntegerField(verbose_name='Payment Allowance (days)'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_uuid',
            field=models.UUIDField(default=uuid.UUID('e1325a5e-8e5f-435c-a2eb-ea6d1b6b6066'), verbose_name='UUID'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='Paid'),
        ),
        migrations.AlterField(
            model_name='timesheetentry',
            name='description_set',
            field=models.BooleanField(default=False, verbose_name='Description has been set'),
        ),
        migrations.AlterField(
            model_name='timesheetentry',
            name='is_invoiced',
            field=models.BooleanField(default=False, verbose_name='Invoiced'),
        ),
    ]
