# Generated by Django 5.2.1 on 2025-06-20 10:00

import datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pjimcrm', '0005_timesheetentry_entry_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='invoice_uuid',
            field=models.UUIDField(default=uuid.UUID('60e5760b-9ecd-4639-ba6a-b0a2b92198a0'), verbose_name='UUID'),
        ),
        migrations.AlterField(
            model_name='timesheetentry',
            name='entry_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Date'),
        ),
    ]
